title: stardew-ja-honyaku
permalink: pretty
timezone: Asia/Tokyo
author_name: "管理人"

# GitHub Pages (project site) — ここを必ず設定
url: "https://takasshi.github.io"
baseurl: "/stardew-ja-honyaku"

# Markdownの安定化（任意：推奨）
markdown: kramdown
kramdown:
  xhtml: false      # <br />, <img /> などを HTML5 形式に
  hard_wrap: false  # 行末スペース2つ以外では <br> を作らない
  input: GFM
