source "https://rubygems.org"

gem "jekyll", "~> 4.4"

# Ruby 3系で必要になることが多い
gem "webrick"

# Windows向け
gem "tzinfo-data", platforms: %i[mingw mswin x64_mingw jruby]
gem "wdm",         platforms: %i[mingw mswin x64_mingw jruby]
